name: dash_survey
description: Extensive remote controlled survey package
version: 0.0.1
repository: https://github.com/ChrisMarxDev/dash-survey
homepage: https://dash-survey.com

environment:
  sdk: "^3.6.0"
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  # dash_survey_core:
  # path: ../dash_survey_core
  dash_survey_core: ^0.0.1
  flutter:
    sdk: flutter
  shared_preferences: ">=2.3.5  <3.0.0"
  uuid: ">=4.3.0 <5.0.0"
  wolt_modal_sheet: ">=0.9.4  <1.0.0"

dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
