name: dash_survey_core
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none


environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  dart_mappable: ^4.3.0
  http: ^1.2.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
