name: dash_survey_core
description: Core package for dash survey
version: 0.0.1+1
repository: https://github.com/ChrisMarxDev/dash-survey
homepage: https://dash-survey.com

resolution: workspace
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  dart_mappable: ">=4.3.0 <5.0.0"
  http: ">=1.0.0 <2.0.0"
  uuid: ">=4.3.0 <5.0.0"

dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
